# Generated by Django 3.2.8 on 2021-10-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_quiz_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerwithchoice',
            old_name='quiz',
            new_name='question',
        ),
    ]
