# Generated by Django 3.2.8 on 2021-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_quiz_answerwithchoice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerswithtext',
            name='answer_status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('not_checked', 'not_checked')], default='not_checked', max_length=30),
        ),
    ]
