# Generated by Django 3.2.8 on 2021-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211021_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerswithchoices',
            name='answer_status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=30),
        ),
    ]
