# Generated by Django 3.2.8 on 2021-10-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_answerwithchoice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerswithchoices',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
    ]
