# Generated by Django 3.2.8 on 2021-10-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_useranswerswithchoices_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerswithchoices',
            name='answer_status',
            field=models.BooleanField(default=False),
        ),
    ]
